import * as wjcCore from '@grapecity/wijmo'
import '@grapecity/wijmo.vue2.core'
import '@grapecity/wijmo.vue2.input'
import '@grapecity/wijmo.vue2.grid'
import '@grapecity/wijmo.vue2.grid.sheet'
import '@grapecity/wijmo.vue2.grid.filter'
import '@grapecity/wijmo.vue2.gauge'
import '@grapecity/wijmo.vue2.chart'
import '@grapecity/wijmo.vue2.chart.interaction'
import '@grapecity/wijmo.vue2.chart.finance'
import '@grapecity/wijmo.vue2.chart.annotation'
import '@grapecity/wijmo.vue2.chart.animation'
import '@grapecity/wijmo.vue2.chart.analytics'
import '@grapecity/wijmo.vue2.chart.hierarchical'

// let domain = window.location.href.split('//')[1].split('/')[0].split(':')[0]
// let license

wjcCore.setLicenseKey('10.250.172.47|eap.svr.miip.skcc.com|eap.vm.miip.skcc.com|fada.svr.miip.skcc.com|fada.vm.miip.skcc.comsvr.miip.skcc.com|fdc.svr.miip.skcc.com|fdc.vm.miip.skcc.com|iam.svr.miip.skcc.com|iam.vm.miip.skcc.com|mes.svr.miip.skcc.com|mes.vm.miip.skcc.com|skmip.growthsoft.co.kr|spc.svr.miip.skcc.com|spc.vm.miip.skcc.com|vm.miip.skcc.com|www.growthsoft.co.kr,319476879394569#B0rhlWYmxSbvNmLjN6az9CcplWbuIndz9SYkFmZs46bj9yYjt6cuAXap5mLtZnLwFWZs46bj9yYjt6cuAXap5mLyZ7cuAXYlxyN48iM7EjLwUjMuATMiojIz5GRiwiIpMkJDBySThCIkqI1cG008er0iojIh94QiwiI9YTN4kzM9cDO6cDN9EzMiojIklkIs4nIxYXOxAjMiojIyVmdiwSZzxWYmpjIyNHZisnOiwmbBJye0ICRiwiI34TQvkGV5pENXlDc5FlbtdXZtRWQnF5RrkDVBZWT944b5VXYKdkQVxkchhXdrhHZX5WQ9QWQPplayIGMjBlM9NHRDlzNvpkTjJWe9IzKQpWNENza4lUbkRWO9MDMVJHNiF7TQx4d6ZVMyo7b4UlTUFGaHhVa7d5akRWdxMEeSllN6Y6Q5VHT4NGcYRDS4JnemRHdNZ6cV9EcWRkUzNUYShFRTpFWxpGMrdnexJmVNRjZNR6YoFUMwcmb6lUM8hXME54cR3SOHBTS6AXQpBzbQl7KlNFR4Z7ZwQVdXx6NNVDRGxGdz2CUr46b0RGNa5WYVNmRNNVRn5GTSRDTDl5dLdzTCZXb4t4aDdGNJpHdklGVVpWW6YlWrc6RHhDTJRVT53GTFRTRTNnW5c6YFt4TLJ6bKFVe7xEa534SMdnTWpHbINnWLZFRGtkb7sUa9dWeERmWwZ4MHZmI0IyUiwiIzYkRDhDNEdjI0ICSiwiNwYDNzczMzYTM0IicfJye&Qf35VfikEMyIlI0IyQiwiIu3Waz9WZ4hXRgACdlVGaThXZsZEIv5mapdlI0IiTisHL3JSNJ9UUiojIDJCLi86bpNnblRHeFBCIyV6dllmV4J7bwVmUg2Wbql6ViojIOJyes4nILdDOIJiOiMkIsIibvl6cuVGd8VEIgc7bSlGdsVXTg2Wbql6ViojIOJyes4nI4YkNEJiOiMkIsIibvl6cuVGd8VEIgAVQM3EIg2Wbql6ViojIOJyes4nIzMEMCJiOiMkIsISZy36Qg2Wbql6ViojIOJyes4nIVhzNBJiOiMkIsIibvl6cuVGd8VEIgQnchh6QsFWaj9WYulmRg2Wbql6ViojIOJyebpjIkJHUiwiI8QDNwITMgYDMyETOxAjMiojI4J7QiwiIytmLvNmL4Z6bzhGd73mcn9yd7dHLt36YuM6YrNnLwlWat9Sb6xSbvNmLjN6az9CcplWbu4mduMGczxSbvNmLjN6az9CcplWbuIndz9yYwNHLytmLvNmL4Z6bzhGd73mcn9Ccp56azxSbvNmLjN6az9CcplWbu4mduMXZtxSbvNmLjN6az9CcplWbuIndz9ycl5GLt36YuM6YrNnLwlWat9Sb69SbhlGLt36YuM6YrNnLwlWat9ic6NnLtFWas46bj9yYjt6cuAXap5mLtZnLjRmZs46bj9yYjt6cuAXap5mLyZ7cuMGZmxSbvNmLjN6az9CcplWbuIndz56bj9yYjt6cuAXap5mztln')

export default wjcCore
